import type { Metadata } from "next";
import { Outfit, Prata } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";




const outfit = Outfit({
  weight: ["400", "500", "700"], 
  style: ["normal"], 
  subsets: ["latin"], 
});

const prata = Prata({
  weight: ["400"], 
  style: ["normal"],
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "A'GACI ",
  description: "Generated by create next app",
  icons: "/cart.jpg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${outfit.className} ${prata.className} antialiased`}
      >
        <div className="px-4 sm:px-[5vw] md:px-[7vw] lg:px-[9vw]">
          <Navbar />
           {children}
           <Footer />
        </div>
      </body>
    </html>
  );
}
