import { Outfit, Prata } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientProvider from "@/provider/ClientProvider" 
import type { Metadata } from "next";
import { Searchbar } from "@/components/Searchbar";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import QueryProvider from "@/provider/queryProvider";



const outfit = Outfit({
  weight: ["400", "500", "700"], 
  style: ["normal"], 
  subsets: ["latin"], 
});

const prata = Prata({
  weight: ["400"], 
  style: ["normal"],
  subsets: ["latin"], 
});


export const metadata: Metadata = {
  title: "A'GACI ",
  description: "Generated by create next app",
  icons: "/cart.jpg"
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${outfit.className} ${prata.className} antialiased`}
      >
        <div className="px-4 sm:px-[5vw] md:px-[7vw] lg:px-[9vw]">
          <QueryProvider>
        <ClientProvider>
          <ToastContainer/>
          <Navbar />
          <Searchbar />
           {children}
           <Footer />
        </ClientProvider>
        </QueryProvider>
        </div>
      </body>
    </html>
  );
}
